name: secupass
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  persistent_bottom_nav_bar: ^6.2.1
  custom_radio_grouped_button: ^2.2.1
  custom_button_builder: ^0.0.4
  gohashlogin: ^0.0.3
  animated_list_plus: ^0.5.2
  intl: ^0.20.2
  equatable: ^2.0.7
  group_button: ^5.3.4
  group_radio_button: ^1.3.0
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  encrypt: ^5.0.3
  flutter_launcher_icons: ^0.14.4
  crypto: ^3.0.6
  rename_app: ^1.6.5
  shelf: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  assets:
    - assets/app_logo.png
  uses-material-design: true
  generate: true

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart